# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        '_doc': 
        {
            'properties': 
            {
                'accession': 'TEXT',
                # EXAMPLES:
                # 'Q9KVZ7' , 'Q9JHE3' , 'P50583' , 'Q9IAT9' , 'F6ZDS4' , 'Q9Z351' , 'P49443' , 'Q80TJ7' , 'P27922' , 'Q9
                # JII9'
                'component_id': 'NUMERIC',
                # EXAMPLES:
                # '8228' , '6810' , '17715' , '6811' , '8229' , '1316' , '8810' , '8234' , '1317' , '4292'
                'component_type': 'TEXT',
                # EXAMPLES:
                # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTE
                # IN' , 'PROTEIN'
                'description': 'TEXT',
                # EXAMPLES:
                # 'Type-2 restriction enzyme XhoI' , 'Neutral ceramidase' , 'Bis(5'-nucleosyl)-tetraphosphatase [asymmet
                # rical]' , 'Basic phospholipase A2 homolog BnSP-7' , 'Nucleoprotein TPR' , 'Potassium voltage-gated cha
                # nnel subfamily KQT member 2' , 'Protein phosphatase 1A' , 'Histone lysine demethylase PHF8' , 'Sodium-
                # dependent dopamine transporter' , 'C-X-C chemokine receptor type 3'
                'go_slims': 
                {
                    'properties': 
                    {
                        'go_id': 'TEXT',
                        # EXAMPLES:
                        # 'GO:0003677' , 'GO:0005576' , 'GO:0000166' , 'GO:0003674' , 'GO:0003674' , 'GO:0005515' , 'GO:
                        # 0003824' , 'GO:0003682' , 'GO:0005575' , 'GO:0002376'
                    }
                },
                'organism': 'TEXT',
                # EXAMPLES:
                # 'Xanthomonas vasicola' , 'Mus musculus' , 'Homo sapiens' , 'Bothropoides pauloensis' , 'Mus musculus' 
                # , 'Mus musculus' , 'Mus musculus' , 'Mus musculus' , 'Bos taurus' , 'Rattus norvegicus'
                'protein_classifications': 
                {
                    'properties': 
                    {
                        'protein_classification_id': 'NUMERIC',
                        # EXAMPLES:
                        # '1' , '1' , '646' , '601' , '601' , '118' , '646' , '848' , '695' , '554'
                    }
                },
                'sequence': 'TEXT',
                # EXAMPLES:
                # 'MALDLAEYDRLARLGVAQFWDGRSSALENDEERSQGGERSGVLGGRNMDGFLAMIEGIVRKNGLPDAEVCIKGRPNLTLPGYYRPTKLWDVLVFDGKKLVA
                # AVELKSHVGPSFGNNFNNRAEEAIGTAHDLATAIREGILGDQLPPFTGWLILVEDCEKSKRAVRDSSPHFPVFPDFKGASYLTRYEVLCRKLILKGFTPRPQ
                # SLLRPALRVLGATIASFRKPRVCAHLRHGWPAMYPVGQSRIRVNF' , 'MAKRTFSTLEAFLIFLLVIMTVITVALLTLLFVTSGTIENHKDSGNHWFSTT
                # LGSTTTQPPPITQTPNFPSFRNFSGYYIGVGRADCTGQVSDINLMGYGKNGQNARGLLTRLFSRAFILADPDGSNRMAFVSVELCMISQRLRLEVLKRLESK
                # YGSLYRRDNVILSAIHTHSGPAGFFQYTLYILASEGFSNRTFQYIVSGIMKSIDIAHTNLKPGKIFINKGNVANVQINRSPSSYLLNPQSERARYSSNTDKE
                # MLVLKLVDLNGEDLGLISWFAIHPVSMNNSNHFVNSDNMGYAAYLFEQEKNKGYLPGQGPFVAGFASSNLGDVSPNILGPHCVNTGESCDNDKSTCPNGGPS
                # MCMASGPGQDMFESTHIIGRIIYQKAKELYASASQEVTGPVLAAHQWVNMTDVSVQLNATHTVKTCKPALGYSFAAGTIDGVSGLNITQGTTEGDPFWDTLR
                # DQLLGKPSEEIVECQKPKPILLHSGELTIPHPWQPDIVDVQIVTVGSLAIAAIPGELTTMSGRRFREAIKKEFALYGMKDMTVVIAGLSNVYTHYITTYEEY
                # QAQRYEAASTIYGPHTLSAYIQLFRDLAKAIATDTVANMSSGPEPPFFKNLIASLIPNIADRAPIGKHFGDVLQPAKPEYRVGEVVEVIFVGANPKNSAENQ
                # THQTFLTVEKYEDSVADWQIMYNDASWETRFYWHKGILGLSNATIYWHIPDTAYPGIYRIRYFGHNRKQELLKPAVILAFEGISSPFEVVTT' , 'MALRA
                # CGLIIFRRCLIPKVDNNAIEFLLLQASDGIHHWTPPKGHVEPGEDDLETALRETQEEAGIEAGQLTIIEGFKRELNYVARNKPKTVIYWLAEVKDYDVEIRL
                # SHEHQAYRWLGLEEACQLAQFKEMKAALQEGHQFLCSIEA' , 'SFELGKMILQETGKNPAKSYGAYGCNCGVLGRGQPKDATDRCCYVHKCCYKKLTGCD
                # PKKDRYSYSWKDKTIVCGENNPCLKELCECDKAVAICLRENLGTYNKKYRYHLKPFCKKADPC' , 'MTSGGSASRSGHRGVPMTSRGFDGSRRGSLRRAG
                # ARETASEAADGAAPAAGLRASPCSLASPSAAAAVAAIPADMAAVLQQVLERPELNKLPKSTQNKLEKFLAEQQSEIDCLKGRHEKFKVESEQQYFEIEKRLS
                # QSQERLVTETRECQNLRLELEKLNNQVKVLTEKTKELETAQDRNLGIQSQFTRAKEELEAEKRDLIRTNERLSQEVEYLTEDVKRLNEKLKESNTTKGELQL
                # KLDELQASDVAVKYREKRLEQEKELLHNQNSWLNTELKTKTDELLALGREKGNEILELKCNLENKKEEVLRLEEQMNGLKTSNEHLQKHVEDLLTKLKEAKE
                # QQASMEEKFHNELNAHIKLSNLYKSAADDSEAKSNELTRAVDELHKLLKEAGEANKTIQDHLLQVEESKDQMEKEMLEKIGKLEKELENANDLLSATKRKGA
                # ILSEEELAAMSPTAAAVAKIVKPGMKLTELYNAYVETQDQLLLEKQENKRINKYLDEIVKEVEAKAPILKRQREEYERAQKAVASLSAKLEQAMKEIQRLQE
                # DTDKANKHSSVLERDNQRMEIQIKDLSQQIRVLLMELEEARGNHVIRDEEVSSADISSSSEVISQHLVSYRNIEELQQQNQRLLFALRELGETREREEQETT
                # SSKIAELQHKLENSLAELEQLRESRQHQMQLVDSIVRQRDMYRILLSQTTGMAIPLQASSLDDISLLSTPKRSSTSQTVSTPAPEPVIDSTEAIEAKAALKQ
                # LQEIFENYKKEKIDSEKLQNEQLEKLQEQVTDLRSQNTKISTQLDFASKRYEMLQDNVEGYRREITSLQERNQKLTATTQKQEQIINTMTQDLRGANEKLAV
                # AEVRAENLKKEKEMLKLSEVRLSQQRESLLAEQRGQNLLLTNLQTIQGILERSETETKQRLNSQIEKLEHEISHLKKKLENEVEQRHTLTRNLDVQLLDTKR
                # QLDTEINLHLNTKELLKNAQKDIATLKQHLNNMEAQLASQSTQRTGKGQPGDRDDVDDLKSQLRQAEEQVNDLKERLKTSTSNVEQYRAMVTSLEDSLNKEK
                # QVTEEVHKNIEVRLKESAEFQTQLEKKLMEVEKEKQELQDDKRKAIESMEQQLSELKKTLSTVQNEVQEALQRASTALSNEQQARRDCQEQAKIAVEAQNKY
                # ERELMLHAADVEALQAAKEQVSKMTSIRQHLEETTQKAESQLLECKASWEERERVLKDEVSKSVSRCEDLEKQNRLLHDQIEKLSDKVVTSMKDAVQAPLNV
                # SLNEEGKSQEQILEILRFIRREKEIAETRFEVAQVESLRYRQRVELLERELQELQDSLNVEREKVQVTAKTMAQHEELMKKTETMNVVMETNKMLREEKERL
                # EQNLQQMQAKVRKLELDILPLQEANAELSEKSGMLQAEKKLLEEDVKRWKARNQQLINQQKDPDTEEYRKLLSEKEIHTKRIQQLNEEVGRLKAEIARSNAS
                # LTNNQNLIQSLREDLSKARTEKEGIQKDLDAKIIDIQEKVKTITQVKKIGRRYKTQFEELKAQQNKAMETSTQSSGDHQEQHISVQEMQELKDTLSQSETKT
                # KSLEGQVENLQKTLSEKETEARSLQEQTVQLQSELSRLRQDLQDKTTEEQLRQQMNEKTWKTLALAKSKITHLSGVKDQLTKEIEELKQRNGALDQQKDELD
                # VRMTALKSQYEGRISRLERELREHQERHLEQRDEPQEPTNKAPEQQRQITLKTTPASGERGIASTSDPPTANIKPTPVVSTPSKVTAAAMAGNKSTPRASIR
                # PMVTPATVTNPTTTPTATVMPTTQVESQEAMQSEGPVEHVPVFGNASGSVRSTSPNVQPSISQPILTVQQQTQATAFVQPTQQSHPQIEPTNQELSPNIVEV
                # VQSSPVERPSTSTAVFGTVSATPSSSLPKRTREEEEDSTMEAGDQVSEDTVEMPLPKKLKMVTPVGTEEEVMAEESTDGEAETQAYNQDSQDSIGEGVTQGD
                # YTPMEDSEETSQSLQIDLGPLQSDQQTTSSQDGQGKGDDVIVIDSDDEDDDEENDGEHEDYEEDEDDDDDEEDDTGMGDEGEDSNEGTGSADGNDGYEADDA
                # EGGDGTDPGTETEESMGGAESHQRAADSQNSGEGNTSAAESSFSQEVAREQQPTSASERQTPQAPQSPRRPPHPLPPRLTIHAPPQELGPPVQRIQMTRRQS
                # VGRGLQLTPGIGGMQQHFFDDEDRTVPSTPTLVVPHRTDGFAEAIHSPQVAGVPRFRFGPPEDMPQTSSSHSDLGQLASQGGLGMYETPLFLAHEEESGGRS
                # VPTTPLQVAAPVTVFTESTTSDASEHASQSVPMVTTSTGTLSTTNETAAGDDGDEVFVEAESEGISSEAGLEIDSQQEEEPVQASDESDLPSTSQDPPSSSS
                # VDTSSSQPKPFRRVRLQTTLRQGVRGRQFNRQRGISHAMGGRGGINRGNIN' , 'MVQKSRNGGVYPGTSGEKKLKVGFVGLDPGAPDSTRDGALLIAGSE
                # APKRGSVLSKPRTGGAGAGKPPKRNAFYRKLQNFLYNVLERPRGWAFIYHAYVFLLVFSCLVLSVFSTIKEYEKSSEGALYILEIVTIVVFGVEYFVRIWAA
                # GCCCRYRGWRGRLKFARKPFCVIDIMVLIASIAVLAAGSQGNVFATSALRSLRFLQILRMIRMDRRGGTWKLLGSVVYAHSKELVTAWYIGFLCLILASFLV
                # YLAEKGENDHFDTYADALWWGLITLTTIGYGDKYPQTWNGRLLAATFTLIGVSFFALPAGILGSGFALKVQEQHRPKHFEKRRNPAAGLIQSAWRFYATNLS
                # RTDLHSTWQYYERTVTVPMYRLIPPLNQLELLRNLKSKSGLTFRKEPQPEPSPSQKVSLKDRVFSSPRGMAAKGKGSPQAQTVRRSPSADQSLDDSPSKVPK
                # SWSFGDRSRTRQAFRIKGAASRQNSEEASLPGEDIVEDNKSCNCEFVTEDLTPGLKVSIRAVCVMRFLVSKRKFKESLRPYDVMDVIEQYSAGHLDMLSRIK
                # SLQSRIDMIVGPPPPSTPRDKKYPTKGPTAPSRESPQYSPRVDHIVGRGPTITDKDRTKGPAETELPEDPSMMGRLGKVEKQVLSMEKKLDFLVSIYTQRMG
                # IPPAETEAYFGAKEPEPAPPYHSPEDSRDHADKHGCIIKIVRSTSSTGQRNYAAPPAIPPAQCPPSTSWQQSHQRHGTSPVGDHGSLVLRLERSAGMMSCH'
                #  , 'MGAFLDKPKMEKHNAQGQGNGLRYGLSSMQGWRVEMEDAHTAVIGLPSGLETWSFFAVYDGHAGSQVAKYCCEHLLDHITNNQDFRGSAGAPSVENVK
                # NGIRTGFLEIDEHMRVMSEKKHGADRSGSTAVGVLISPQHTYFINCGDSRGLLCRNRKVHFFTQDHKPSNPLEKERIQNAGGSVMIQRVNGSLAVSRALGDF
                # DYKCVHGKGPTEQLVSPEPEVHDIERSEEDDQFIILACDGIWDVMGNEELCDFVRSRLEVTDDLEKVCNEVVDTCLYKGSRDNMSVILICFPSAPKVSAEAV
                # KKEAELDKYLESRVEEIIKKQVEGVPDLVHVMRTLASENIPSLPPGGELASKRNVIEAVYNRLNPYKNDDTDSASTDDMW' , 'MASVPVYCLCRLPYDVT
                # RFMIECDMCQDWFHGSCVGVEEEKAADIDLYHCPNCEVLHGPSIMKKRRGSSKGHDNHKGKPLKTGSSMFIRELRGRTFDSSDEVILKPTGSQLTVEFLEEN
                # SFSVPILVLKKDGLGMTLPSPSFTVRDVEHYVGSDKEIDVIDVARQADCKMKLGDFVKYYYSGKREKVLNVISLEFSDTRLSNLVETPRIVRKLSWVENLWP
                # EECVFERPNVQKYCLMSVRDSYTDFHIDFGGTSVWYHVLKGEKIFYLIRPTNANLTLFECWSSSSNQNEMFFGDQVEKCYKCSVKQGQTLFIPTGWIHAVLT
                # PVDCLAFGGNFLHSLNIEMQLKAYEIEKRLSTADLFKFPNFETICWYVGKHILDIFRGLRENRRHPASYLVHGGKALNLAFRAWTKKEALPDHEDEIPETVR
                # TVQLIKDLAREIRLVEDIFQQNVGKTSNIFGLQRIFPAGSIPLTKPAHSTSVSMSKLSLPSKNGSKKKGLKPKDIFKKAERKGKQSSALGPAGQLSYNLMDP
                # YSHQALKTGPSQKAKFNMSGTSLNDSDDDSADMDLDGSENPLALLMANGSTKRMKSVSKSRRAKIAKKVDSARLVAEQVMGDEFDLDSDDELQIDERLGKEK
                # ANLLIRSKFPRKLPRAKPCSDPNRIREPGEVEFDIEEDYTTDEDMVEGVESKLGNGSGAGGILDLLKASRQVGGPDYAALTEAPASPSTQEAIQGMLCMANL
                # QSSSSSPATSSLQAWWTGGQERSSGSSSSGLGTVSSSPASQRTPGKRPIKRPAYWKNESEEEENASLDEQDSLGACFKDAEYIYPSLESDDDDPALKSRPKK
                # KKNSDDAPWSPKARVTPTLPKQDRPVREGTRVASIETGLAAAAAKLAQQELQKAQKKKYIKKKPLLKEVEQPRPQDSNPIMTMPAPTVATTPQPDTSSSPQP
                # PPEPKQEALSGSLADHEYTARPNAFGMAQANRSTTPMAPGVFLTQRRPSVGSQSSQAGQGKRPKKGLATAKQRLGRILKIHRNGKLLL' , 'MSEGRCSVA
                # HMSSVVAPAKEANAMGPKAVELVLVKEQNGVQLTNSTLLNPPQSPTEAQDRETWSKKADFLLSVIGFAVDLANVWRFPYLCYKNGGGAFLVPYLFFMVVAGV
                # PLFYMELALGQFNREGAAGVWKICPILRGVGYTAILISLYIGFFYNVIIAWALHYLLSSFTTELPWTHCNHSWNSPRCSDARAPNASSGPNGTSRTTPAAEY
                # FERGVLHLHESQGIDDLGPPRWQLTSCLVLVIVLLYFSLWKGVKTSGKVVWITATMPYVVLFALLLRGITLPGAVDAIRAYLSVDFHRLCEASVWIDAAIQI
                # CFSLGVGLGVLIAFSSYNKFTNNCYRDAIITTSVNSLTSFSSGFVVFSFLGYMAQKHSVPIGDVAKDGPGLIFIIYPEALATLPLSSVWAVVFFVMLLTLGI
                # DSAMGGMESVITGLADEFQLLHRHRELFTLLVVLATFLLSLFCVTNGGIYVFTLLDHFAAGTSILFGVLMEVIGVAWFYGVWQFSDDIKQMTGRRPSLYWRL
                # CWKFVSPCFLLFVVVVSIATFRPPHYGAYVFPEWATALGWAIAASSMSVVPIYAAYKLCSLPGSSREKLAYAITPETEHGRVDSGGGAPVHAPPLARGVGRW
                # RKRKSCWVPSRGPGRGGPPTPSPRLAGHTRAFPWTGAPPVPRELTPPSTCRCVPPLVCAHPAVESTGLCSVY' , 'MYLEVSERQVLDASDIAFLLENSTS
                # PYDYGENESDFSDSPPCPQDFSLNFDRTFLPVLYSLLFLLGLLGNGAVAAVLLSQRTALSSTDTFLLHLAVADVLLVLTLPLWAVDAAAQWVFGSGLCKVAG
                # ALFNINFYAGAFLLACISFDRYLSIVHATQIYRRDPWVRVALTCIVVWGLCVLFALPDFIFLSASHDQRLNATHCQYNFPQVGRTALRVLQLVAGFLMPLLV
                # MAYCYAHILAVLLVSRGQRRFRAMRLVVVVVVAFAVCWTPYHLVVLVDILMDVGVLARNCGRESHVDVAKSVTSGMGYMHCCLNPLLYAFVGVKFKEQMWML
                # LMRLGRSDQRGPQRQPSSSRRESSWSETTEASYLGL'
                'target_component_synonyms': 
                {
                    'properties': 
                    {
                        'component_synonym': 'TEXT',
                        # EXAMPLES:
                        # '3.1.21.4' , '3.5.1.23' , '3.6.1.17' , 'Basic phospholipase A2 homolog BnSP-7' , 'NPC-associat
                        # ed intranuclear protein' , 'KQT-like 2' , '3.1.3.16' , '1.14.11.27' , 'DA transporter' , 'C-X-
                        # C chemokine receptor type 3'
                        'syn_type': 'TEXT',
                        # EXAMPLES:
                        # 'EC_NUMBER' , 'EC_NUMBER' , 'EC_NUMBER' , 'UNIPROT' , 'UNIPROT' , 'UNIPROT' , 'EC_NUMBER' , 'E
                        # C_NUMBER' , 'UNIPROT' , 'UNIPROT'
                    }
                },
                'target_component_xrefs': 
                {
                    'properties': 
                    {
                        'xref_id': 'TEXT',
                        # EXAMPLES:
                        # 'GO:0003677' , 'Q9JHE3' , 'ENSG00000164978' , 'GO:0005576' , 'F6ZDS4' , 'GO:0005886' , 'P49443
                        # ' , 'Q80TJ7' , 'GO:0005886' , 'Q9JII9'
                        'xref_name': 'TEXT',
                        # EXAMPLES:
                        # 'DNA binding' , 'extracellular region' , 'mitochondrial matrix' , 'extracellular region' , 'ch
                        # romosome, centromeric region' , 'plasma membrane' , 'nucleus' , 'nucleus' , 'plasma membrane' 
                        # , 'plasma membrane'
                        'xref_src_db': 'TEXT',
                        # EXAMPLES:
                        # 'GoFunction' , 'ExpressionAtlas' , 'EnsemblGene' , 'GoComponent' , 'ExpressionAtlas' , 'GoComp
                        # onent' , 'ExpressionAtlas' , 'ExpressionAtlas' , 'GoComponent' , 'ExpressionAtlas'
                    }
                },
                'targets': 
                {
                    'properties': 
                    {
                        'target_chembl_id': 'TEXT',
                        # EXAMPLES:
                        # 'CHEMBL2439945' , 'CHEMBL2146344' , 'CHEMBL4105863' , 'CHEMBL2146345' , 'CHEMBL3038516' , 'CHE
                        # MBL2985' , 'CHEMBL3309056' , 'CHEMBL3038497' , 'CHEMBL2986' , 'CHEMBL1075172'
                    }
                },
                'tax_id': 'NUMERIC',
                # EXAMPLES:
                # '56459' , '10090' , '9606' , '1042543' , '10090' , '10090' , '10090' , '10090' , '9913' , '10116'
            }
        }
    }
