# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        '_doc': 
        {
            'properties': 
            {
                'biocomponents': 
                {
                    'properties': 
                    {
                        'component_id': 'NUMERIC',
                        # EXAMPLES:
                        # '17454' , '17456' , '17457' , '17459' , '17461' , '17463' , '17465' , '17469' , '17471' , '174
                        # 73'
                        'component_type': 'TEXT',
                        # EXAMPLES:
                        # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' 
                        # , 'PROTEIN' , 'PROTEIN'
                        'description': 'TEXT',
                        # EXAMPLES:
                        # 'EMAPALUMAB Heavy chain' , 'LARCAVIXIMAB Heavy chain' , 'COFETUZUMAB Heavy chain' , 'COFETUZUM
                        # AB PELIDOTIN Heavy chain' , 'NAVICIXIZUMAB Anti-DLL4 heavy chain' , 'RAVULIZUMAB Heavy chain' 
                        # , 'MODOTUXIMAB Heavy chain' , 'ISTIRATUMAB Heavy chain' , 'ROVALPITUZUMAB Heavy chain' , 'PORG
                        # AVIXIMAB Heavy chain'
                        'organism': 'TEXT',
                        # EXAMPLES:
                        # 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sap
                        # iens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens'
                        'sequence': 'TEXT',
                        # EXAMPLES:
                        # 'RIHMVYSKRSGKPRGYAFIEY' , 'L1NFRAPPVIPNVPFLWAWNAPSEFCLGK1FDEPLDMSLFSFIGSPRINATGQGVTIFYVDRLGYYP
                        # YIDSITGVTVNGGIPQK1ISLQDHLDK1AK1K1DITFYMPVDNLGMAVIDWEEWRPTWARNWK1PK1DVYK1NRSIELVQQQNVQLSLTEATEK
                        # 1AK1QEFEK1AGK1DFLVETIK1LGK1LLRPNHLWGYYLFPDCYNHHYK1K1PGYNGSCFNVEIK1RNDDLSWLWNESTALYPSIYLNTQQSPV
                        # AATLYVRNRVREAIRVSK1IPDAK1SPLPVFAYTRIVFTDQVLK1FLSQDELVYTFGETVALGASGIVIWGTLSIMRSMK1SCLLLDNYMETIL
                        # NPYIINVTLAAK1MCSQVLCQEQGVCIRK1NWNSSDYLHLNPDNFAIQLEK1GGK1FTVRGK1PTLEDLEQFSEK1FYCSCYSTLSCK1EK1AD
                        # VK1DTDAVDVCIADGVCIDAFLK1PPMETEEPQIFY' , 'EVQLLESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISG
                        # SGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKDGSSGWYVPHWFDPWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAA
                        # LGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPKSCDKTHTCPPCPAPELL
                        # GGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALP
                        # APIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVF
                        # SCSVMHEALHNHYTQKSLSLSPGK' , 'EVQLQESGPELEMPGASVKISCKASGSSFTGFSMNWVKQSNGKSLEWIGNIDTYYGGTTYNQKFK
                        # GKATLTVDKSSSTAYMQLKSLTSEDSAVYYCARSAYYGSTFAYWGQGTLVTVSAASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVS
                        # WNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTL
                        # MISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPRE
                        # PQVYTLPPSRDELTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQK
                        # SLSLSPGK' , 'Q1VQLVQSGPEVKKPGASVKVSCKASGYTFTDYAVHWVRQAPGKRLEWIGVISTYNDYTYNNQDFKGRVTMTRDTSASTAY
                        # MELSRLRSDTAVYYCARGNSYFYALDYWGQGTSVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAV
                        # LQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVS
                        # HEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKN
                        # QVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPG' , 'Q1VQ
                        # LVQSGPEVKKPGASVKVSCKASGYTFTDYAVHWVRQAPGKRLEWIGVISTYNDYTYNNQDFKGRVTMTRDTSASTAYMELSRLRSEDTAVYYCA
                        # RGNSYFYALDYWGQGTSVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVP
                        # SSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVE
                        # VHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSRDELTKNQVSLTCLVKGFYPSDI
                        # AVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPG' , 'QVQLVQSGAEVKKPGASVKI
                        # SCKASGYSFTAYYIHWVKQAPGQGLEWIGYISNYNRATNYNQKFKGRVTFTTDTSTSTAYMELRSLRSDDTAVYYCARDYDYDVGMDYWGQGTL
                        # VTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSNFGTQTYTCNVDHKP
                        # SNTKVDKTVERKCCVECPPCPAPPVAGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTFRVVS
                        # VLTVVHQDWLNGKEYKCKVSNKGLPAPIEKTISKTKGQPREPQVYTLPPSREEMTKNQVSLTCLVEGFYPSDIAVEWESNGQPENNYKTTPPML
                        # DSDGSFFLYSELTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK' , 'Q1VQLVQSGAEVKKPGASVKVSCKASGHIFSNYWIQWVRQ
                        # APGQGLEWMGEILPGSGHTEYTENFKDRVTMTRDTSTSTVYMELSSLRSEDTAVYYCARYFFGSSPNWYFDVWGQGTLVTVSSASTKGPSVFPL
                        # APCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSNFGTQTYTCNVDHKPSNTKVDKTVERKCCVE
                        # CPPCPAPPVAGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYK
                        # CKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDK
                        # SRWQEGNVFSCSVLHEALHSHYTQKSLSLSLG' , 'QVQLQQPGAELVEPGGSVKLSCKASGYTFTSHWMHWVKQRPGQGLEWIGEINPSSGR
                        # NNYNEKFKSKATLTVDKSSSTAYMQFSSLTSEDSAVYYCVRYYGYDEAMDYWGQGTSVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDY
                        # FPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPKSCDKTHTCPPCPAPELLGGPSVFLF
                        # PPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTIS
                        # KAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEA
                        # LHNHYTQKSLSLSPG' , 'EVQLLQSGGGLVQPGGSLRLSCAASGFMFSRYPMHWVRQAPGKGLEWVGSISGSGGATPYADSVKGRFTISRDN
                        # SKNTLYLQMNSLRAEDTAVYYCAKDFYQILTGNAFDYWGQGTTVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGAL
                        # TSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTP
                        # EVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTIKAKGQPREPQVYTLP
                        # PSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPG
                        # GGGGSGGGGSGGGGSQVQLVQSGGGLVQPGGSLRLSCAASGFTFDDYAMHWVRQAPGKGLEWVAGISWDSGSTGYADSVKGRFTISRDNAKNSL
                        # YLQMNSLRAEDTALYYCARDLGAYQWVEGFDYWGQGTLVTVSSASTGGGGSGGGGSGGGGSGGGGSSYELTQDPAVSVALGQTVRITCQGDSLR
                        # SYYASWYQQKPGQAPVLVIYGKNNRPSGIPDRFSGSTSGNSASLTITGAQAEDEADYYCNSRDSPGNQWVFGGGTKVTVLG'
                        'tax_id': 'NUMERIC',
                        # EXAMPLES:
                        # '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '9606' , '9606'
                    }
                },
                'description': 'TEXT',
                # EXAMPLES:
                # 'OPIORPHIN (3-5)' , 'OPIORPHIN (2-5)' , 'BOMBESIN' , 'OPIORPHIN (1-4)' , 'EFEGATRAN' , 'LOLOATIN A' , 
                # 'LOLOATIN C' , 'LOLOATIN D' , 'PHAKELLISTATIN 2' , 'PHAKELLISTATIN 2 (SYNTHETIC)'
                'helm_notation': 'TEXT',
                # EXAMPLES:
                # 'PEPTIDE1{[dC].[dD].G.[X347].G.[Hyp].N.[dC].[am]}$PEPTIDE1,PEPTIDE1,8:R3-1:R3$$$' , 'PEPTIDE1{[EtCO_F]
                # .K.A.[Nle].[am]}$$$$' , 'PEPTIDE1{[dR].[dP].K.[dP].[dQ].[dQ].F.F.G.L.M.[am]}$$$$' , 'PEPTIDE1{[X2156].
                # [X2582].[X1197]}$PEPTIDE1,PEPTIDE1,3:R2-1:R1$$$' , 'PEPTIDE1{K.L.K.K.L.L.K.K.L.K.K.L.L.K}$$$$' , 'PEPT
                # IDE1{[dQ].Q.[dK].H.S.N.R.K.L.[Nle].E.I.I.[am]}|PEPTIDE2{[dF].H.L.L.R.E.V.L.E.[Nle].A.R.A.E.Q.L.[dE]}$P
                # EPTIDE2,PEPTIDE1,17:R2-1:R1|PEPTIDE2,PEPTIDE1,17:R3-3:R3$$$' , 'PEPTIDE1{[ac].P.S.P.W.A.T.C.D.A.[am]}$
                # $$$' , 'PEPTIDE1{[ac].F.Q.S.K.Q.N.V.F.Y.D.G.Y.F.E.R.L.C.I.K.L.[am]}$$$$' , 'PEPTIDE1{R.P.P.G.F.S.P.D}$
                # $$$' , 'PEPTIDE1{[ac].A.R.A.E.V.H.L.[am]}$$$$'
                'molecule_chembl_id': 'TEXT',
                # EXAMPLES:
                # 'CHEMBL573006' , 'CHEMBL78541' , 'CHEMBL386568' , 'CHEMBL1793821' , 'CHEMBL225883' , 'CHEMBL2370520' ,
                #  'CHEMBL3397431' , 'CHEMBL3943262' , 'CHEMBL2372161' , 'CHEMBL1086453'
            }
        }
    }
