# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        'properties': 
        {
            'accession': 'TEXT',
            # EXAMPLES:
            # 'P13516' , 'P24046' , 'P0A8T7' , 'P00395' , 'Q9NP99' , 'P00329' , 'B2G369' , 'O75038' , 'Q16637' , 'Q9Y2U5
            # '
            'component_id': 'NUMERIC',
            # EXAMPLES:
            # '3649' , '1882' , '7858' , '4752' , '5249' , '1688' , '18500' , '956' , '5147' , '4388'
            'component_type': 'TEXT',
            # EXAMPLES:
            # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' 
            # , 'PROTEIN'
            'description': 'TEXT',
            # EXAMPLES:
            # 'Acyl-CoA desaturase 1' , 'Gamma-aminobutyric acid receptor subunit rho-1' , 'DNA-directed RNA polymerase 
            # subunit beta'' , 'Cytochrome c oxidase subunit 1' , 'Triggering receptor expressed on myeloid cells 1' , '
            # Alcohol dehydrogenase 1' , 'Polymerase 3D' , '1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase et
            # a-2' , 'Survival motor neuron protein' , 'Mitogen-activated protein kinase kinase kinase 2'
            'go_slims': 
            {
                'properties': 
                {
                    'go_id': 'TEXT',
                    # EXAMPLES:
                    # 'GO:0005730' , 'GO:0003674' , 'GO:0003677' , 'GO:0003674' , 'GO:0002376' , 'GO:0003674' , 'GO:0003
                    # 723' , 'GO:0003674' , 'GO:0003723' , 'GO:0000166'
                }
            },
            'organism': 'TEXT',
            # EXAMPLES:
            # 'Mus musculus' , 'Homo sapiens' , 'Escherichia coli K-12' , 'Homo sapiens' , 'Homo sapiens' , 'Mus musculu
            # s' , 'Human enterovirus 71 STH/MCN/2006' , 'Homo sapiens' , 'Homo sapiens' , 'Homo sapiens'
            'protein_classifications': 
            {
                'properties': 
                {
                    'protein_classification_id': 'NUMERIC',
                    # EXAMPLES:
                    # '10' , '1173' , '643' , '744' , '601' , '10' , '601' , '1' , '860' , '419'
                }
            },
            'sequence': 'TEXT',
            # EXAMPLES:
            # 'MPAHMLQEISSSYTTTTTITAPPSGNEREKVKTVPLHLEEDIRPEMKEDIHDPTYQDEEGPPPKLEYVWRNIILMVLLHLGGLYGIILVPSCKLYTCLFGIFYYM
            # TSALGITAGAHRLWSHRTYKARLPLRIFLIIANTMAFQNDVYEWARDHRAHHKFSETHADPHNSRRGFFFSHVGWLLVRKHPAVKEKGGKLDMSDLKAEKLVMFQR
            # RYYKPGLLLMCFILPTLVPWYCWGETFVNSLFVSTFLRYTLVLNATWLVNSAAHLYGYRPYDKNIQSRENILVSLGAVGEGFHNYHHTFPFDYSASEYRWHINFTT
            # FFIDCMAALGLAYDRKKVSKATVLARIKRTGDGSHKSS' , 'MLAVPNMRFGIFLLWWGWVLATESRMHWPGREVHEMSKKGRPQRQRREVHEDAHKQVSPILRR
            # SPDITKSPLTKSEQLLRIDDHDFSMRPGFGGPAIPVGVDVQVESLDSISEVDMDFTMTLYLRHYWKDERLSFPSTNNLSMTFDGRLVKKIWVPDMFFVHSKRSFIH
            # DTTTDNVMLRVQPDGKVLYSLRVTVTAMCNMDFSRFPLDTQTCSLEIESYAYTEDDLMLYWKKGNDSLKTDERISLSQFLIQEFHTTTKLAFYSSTGWYNRLYINF
            # TLRRHIFFFLLQTYFPATLMVMLSWVSFWIDRRAVPARVPLGITTVLTMSTIITGVNASMPRVSYIKAVDIYLWVSFVFVFLSVLEYAAVNYLTTVQERKEQKLRE
            # KLPCTSGLPPPRTAMLDGNYSDGEVNDLDNYMPENGEKPDRMMVQLTLASERSSPQRKSQRSSYVSMRIDTHAIDKYSRIIFPAAYILFNLIYWSIFS' , 'MKD
            # LLKFLKAQTKTEEFDAIKIALASPDMIRSWSFGEVKKPETINYRTFKPERDGLFCARIFGPVKDYECLCGKYKRLKHRGVICEKCGVEVTQTKVRRERMGHIELAS
            # PTAHIWFLKSLPSRIGLLLDMPLRDIERVLYFESYVVIEGGMTNLERQQILTEEQYLDALEEFGDEFDAKMGAEAIQALLKSMDLEQECEQLREELNETNSETKRK
            # KLTKRIKLLEAFVQSGNKPEWMILTVLPVLPPDLRPLVPLDGGRFATSDLNDLYRRVINRNNRLKRLLDLAAPDIIVRNEKRMLQEAVDALLDNGRRGRAITGSNK
            # RPLKSLADMIKGKQGRFRQNLLGKRVDYSGRSVITVGPYLRLHQCGLPKKMALELFKPFIYGKLELRGLATTIKAAKKMVEREEAVVWDILDEVIREHPVLLNRAP
            # TLHRLGIQAFEPVLIEGKAIQLHPLVCAAYNADFDGDQMAVHVPLTLEAQLEARALMMSTNNILSPANGEPIIVPSQDVVLGLYYMTRDCVNAKGEGMVLTGPKEA
            # ERLYRSGLASLHARVKVRITEYEKDANGELVAKTSLKDTTVGRAILWMIVPKGLPYSIVNQALGKKAISKMLNTCYRILGLKPTVIFADQIMYTGFAYAARSGASV
            # GIDDMVIPEKKHEIISEAEAEVAEIQEQFQSGLVTAGERYNKVIDIWAAANDRVSKAMMDNLQTETVINRDGQEEKQVSFNSIYMMADSGARGSAAQIRQLAGMRG
            # LMAKPDGSIIETPITANFREGLNVLQYFISTHGARKGLADTALKTANSGYLTRRLVDVAQDLVVTEDDCGTHEGIMMTPVIEGGDVKEPLRDRVLGRVTAEDVLKP
            # GTADILVPRNTLLHEQWCDLLEENSVDAVKVRSVVSCDTDFGVCAHCYGRDLARGHIINKGEAIGVIAAQSIGEPGTQLTMRTFHIGGAASRAAAESSIQVKNKGS
            # IKLSNVKSVVNSSGKLVITSRNTELKLIDEFGRTKESYKVPYGAVLAKGDGEQVAGGETVANWDPHTMPVITEVSGFVRFTDMIDGQTITRQTDELTGLSSLVVLD
            # SAERTAGGKDLRPALKIVDAQGNDVLIPGTDMPAQYFLPGKAIVQLEDGVQISSGDTLARIPQESGGTKDITGGLPRVADLFEARRPKEPAILAEISGIVSFGKET
            # KGKRRLVITPVDGSDPYEEMIPKWRQLNVFEGERVERGDVISDGPEAPHDILRLRGVHAVTRYIVNEVQDVYRLQGVKINDKHIEVIVRQMLRKATIVNAGSSDFL
            # EGEQVEYSRVKIANRELEANGKVGATYSRDLLGITKASLATESFISAASFQETTRVLTEAAVAGKRDELRGLKENVIVGRLIPAGTGYAYHQDRMRRRAAGEAPAA
            # PQVTAEDASASLAELLNAGLGGSDNE' , 'MFADRWLFSTNHKDIGTLYLLFGAWAGVLGTALSLLIRAELGQPGNLLGNDHIYNVIVTAHAFVMIFFMVMPIMI
            # GGFGNWLVPLMIGAPDMAFPRMNNMSFWLLPPSLLLLLASAMVEAGAGTGWTVYPPLAGNYSHPGASVDLTIFSLHLAGVSSILGAINFITTIINMKPPAMTQYQT
            # PLFVWSVLITAVLLLLSLPVLAAGITMLLTDRNLNTTFFDPAGGGDPILYQHLFWFFGHPEVYILILPGFGMISHIVTYYSGKKEPFGYMGMVWAMMSIGFLGFIV
            # WAHHMFTVGMDVDTRAYFTSATMIIAIPTGVKVFSWLATLHGSNMKWSAAVLWALGFIFLFTVGGLTGIVLANSSLDIVLHDTYYVVAHFHYVLSMGAVFAIMGGF
            # IHWFPLFSGYTLDQTYAKIHFTIMFIGVNLTFFPQHFLGLSGMPRRYSDYPDAYTTWNILSSVGSFISLTAVMLMIFMIWEAFASKRKVLMVEEPSMNLEWLYGCP
            # PPYHTFEEPVYMKS' , 'MRKTRLWGLLWMLFVSELRAATKLTEEKYELKEGQTLDVKCDYTLEKFASSQKAWQIIRDGEMPKTLACTERPSKNSHPVQVGRIIL
            # EDYHDHGLLRVRMVNLQVEDSGLYQCVIYQPPKEPHMLFDRIRLVVTKGFSGTPGSNENSTQNVYKIPPTTTKALCPLYTSPRTVTQAPPKSTADVSTPDSEINLT
            # NVTDIIRVPVFNIVILLAGGFLSKSLVFSVLFAVTLRSFVP' , 'MSTAGKVIKCKAAVLWELHKPFTIEDIEVAPPKAHEVRIKMVATGVCRSDDHVVSGTLVT
            # PLPAVLGHEGAGIVESVGEGVTCVKPGDKVIPLFSPQCGECRICKHPESNFCSRSDLLMPRGTLREGTSRFSCKGKQIHNFISTSTFSQYTVVDDIAVAKIDGASP
            # LDKVCLIGCGFSTGYGSAVKVAKVTPGSTCAVFGLGGVGLSVIIGCKAAGAARIIAVDINKDKFAKAKELGATECINPQDYSKPIQEVLQEMTDGGVDFSFEVIGR
            # LDTMTSALLSCHAACGVSVVVGVPPNAQNLSMNPMLLLLGRTWKGAIFGGFKSKDSVPKLVADFMAKKFPLDPLITHVLPFEKINEAFDLLRSGKSIRTVLTF' ,
            #  'GEIQWMKPNKETGRLNINGPTRTKLEPSVFHDVFEGTKEPAVLTSKDPRLEVDFEQALFSKYVGNTLHEPDEFVKEAALHYANQLKQLDIKTTKMSMEDACYGT
            # ENLEAIDLHTSAGYPYSALGIKKRDILDPTTRDVSKMKFYMDKYGLDLPYSTYVKDELRAIDKIKKGKSRLIEASSLNDSVYLRMTFGHLYEVFHANPGTVTGSAV
            # GCNPDVFWSKLPILLPGSLFAFDYSGYDASLSPVWFRALEIVLREIGYSEDAVSLIEGINHTHHVYRNTTYCVLGGMPSGCSGTSIFNSMINNIIIRTLLIKTFKG
            # IDLDELNMVAYGDDVLASYPFPIDCLELAKTGKEYGLTMTPADKSPCFNEVTWENATFLKRGFLPDHQFPFLIHPTMPMREIHESIRWTKDARSTQDHVRSLCLLA
            # WHNGKEEYEKFVSTIRSVPIGKALAIPNFENLRRNWLELF' , 'MSGPWPSPDSRTKGTVAWLAEVLLWVGGSVVLSSEWQLGPLVERCMGAMQEGMQMVKLRGG
            # SKGLVRFYYLDEHRSCIRWRPSRKNEKAKISIDSIQEVSEGRQSEVFQRYPDGSFDPNCCFSIYHGSHRESLDLVSTSSEVARTWVTGLRYLMAGISDEDSLARRQ
            # RTRDQWLKQTFDEADKNGDGSLSIGEVLQLLHKLNVNLPRQRVKQMFREADTDDHQGTLGFEEFCAFYKMMSTRRDLYLLMLTYSNHKDHLDAASLQRFLQVEQKM
            # AGVTLESCQDIIEQFEPCPENKSKGLLGIDGFTNYTRSPAGDIFNPEHHHVHQDMTQPLSHYFITSSHNTYLVGDQLMSQSRVDMYAWVLQAGCRCVEVDCWDGPD
            # GEPIVHHGYTLTSKILFKDVIETINKYAFIKNEYPVILSIENHCSVIQQKKMAQYLTDILGDKLDLSSVSSEDATTLPSPQMLKGKILVKGKKLPANISEDAEEGE
            # VSDEDSADEIDDDCKLLNGDASTNRKRVENTAKRKLDSLIKESKIRDCEDPNNFSVSTLSPSGKLGRKSKAEEDVESGEDAGASRRNGRLVVGSFSRRKKKGSKLK
            # KAASVEEGDEGQDSPGGQSRGATRQKKTMKLSRALSDLVKYTKSVATHDIEMEAASSWQVSSFSETKAHQILQQKPAQYLRFNQQQLSRIYPSSYRVDSSNYNPQP
            # FWNAGCQMVALNYQSEGRMLQLNRAKFSANGGCGYVLKPGCMCQGVFNPNSEDPLPGQLKKQLVLRIISGQQLPKPRDSMLGDRGEIIDPFVEVEIIGLPVDCSRE
            # QTRVVDDNGFNPTWEETLVFMVHMPEIALVRFLVWDHDPIGRDFIGQRTLAFSSMMPGYRHVYLEGMEEASIFVHVAVSDISGKVKQALGLKGLFLRGPKPGSLDS
            # HAAGRPPARPSVSQRILRRTASAPTKSQKPGRRGFPELVLGTRDTGSKGVADDVVPPGPGPAPEAPAQEGPGSGSPRDTRPLSTQRPLPPLCSLETIAEEPAPGPG
            # PPPPAAVPTSSSQGRPPYPTGPGANVASPLEDTEEPRDSRPRPCNGEGAGGAYERAPGSQTDGRSQPRTLGHLPVIRRVKSEGQVPTEPLGGWRPLAAPFPAPAVY
            # SDATGSDPLWQRLEPCGHRDSVSSSSSMSSSDTVIDLSLPSLGLGRSRENLAGAHMGRLPPRPHSASAARPDLPPVTKSKSNPNLRATGQRPPIPDELQPRSLAPR
            # MAGLPFRPPWGCLSLVGVQDCPVAAKSKSLGDLTADDFAPSFEGGSRRLSHSLGLPGGTRRVSGPGVRRDTLTEQLRWLTVFQQAGDITSPTSLGPAGEGVAGGPG
            # FVRRSSSRSHSRVRAIASRARQAQERQQRLQGLGRQGPPEEERGTPEGACSVGHEGSVDAPAPSKGALGPASAAAENLVLLRL' , 'MAMSSGGSGGGVPEQEDS
            # VLFRRGTGQSDDSDIWDDTALIKAYDKAVASFKHALKNGDICETSGKPKTTPKRKPAKKNKSQKKNTAASLQQWKVGDKCSAIWSEDGCIYPATIASIDFKRETCV
            # VVYTGYGNREEQNLSDLLSPICEVANNIEQNAQENENESQVSTDESENSRSPGNKSDNIKPKSAPWNSFLPPPPPMPGPRLGPGKPGLKFNGPPPPPPPPPPHLLS
            # CWLPPFPSGPPIIPPPPPICPDSLDDADALGSMLISWYMSGYHTGYYMGFRQNQKEGRCSHSLN' , 'MDDQQALNSIMQDLAVLHKASRPALSLQETRKAKSSS
            # PKKQNDVRVKFEHRGEKRILQFPRPVKLEDLRSKAKIAFGQSMDLHYTNNELVIPLTTQDDLDKAVELLDRSIHMKSLKILLVINGSTQATNLEPLPSLEDLDNTV
            # FGAERKKRLSIIGPTSRDRSSPPPGYIPDELHQVARNGSFTSINSEGEFIPESMDQMLDPLSLSSPENSGSGSCPSLDSPLDGESYPKSRMPRAQSYPDNHQEFSD
            # YDNPIFEKFGKGGTYPRRYHVSYHHQEYNDGRKTFPRARRTQGTSLRSPVSFSPTDHSLSTSSGSSIFTPEYDDSRIRRRGSDIDNPTLTVMDISPPSRSPRAPTN
            # WRLGKLLGQGAFGRVYLCYDVDTGRELAVKQVQFDPDSPETSKEVNALECEIQLLKNLLHERIVQYYGCLRDPQEKTLSIFMEYMPGGSIKDQLKAYGALTENVTR
            # KYTRQILEGVHYLHSNMIVHRDIKGANILRDSTGNVKLGDFGASKRLQTICLSGTGMKSVTGTPYWMSPEVISGEGYGRKADIWSVACTVVEMLTEKPPWAEFEAM
            # AAIFKIATQPTNPKLPPHVSDYTRDFLKRIFVEAKLRPSADELLRHMFVHYH'
            'target_component_synonyms': 
            {
                'properties': 
                {
                    'component_synonym': 'TEXT',
                    # EXAMPLES:
                    # '1.14.19.1' , 'GABA(A) receptor subunit rho-1' , '2.7.7.6' , '1.9.3.1' , 'CD_antigen=CD354' , '1.1
                    # .1.1' , '3D' , '1-phosphatidylinositol 4,5-bisphosphate phosphodiesterase eta-2' , 'Component of g
                    # ems 1' , '2.7.11.25'
                    'syn_type': 'TEXT',
                    # EXAMPLES:
                    # 'EC_NUMBER' , 'UNIPROT' , 'EC_NUMBER' , 'EC_NUMBER' , 'UNIPROT' , 'EC_NUMBER' , 'GENE_SYMBOL' , 'U
                    # NIPROT' , 'UNIPROT' , 'EC_NUMBER'
                }
            },
            'target_component_xrefs': 
            {
                'properties': 
                {
                    'xref_id': 'TEXT',
                    # EXAMPLES:
                    # 'P13516' , 'ENSG00000146276' , 'GO:0005737' , 'MT-CO1' , 'ENSG00000124731' , 'P00329' , 'GO:000372
                    # 3' , 'ENSG00000149527' , 'SMN1' , 'ENSG00000169967'
                    'xref_name': 'TEXT',
                    # EXAMPLES:
                    # 'nucleolus' , 'plasma membrane' , 'cytoplasm' , 'Deafness, mitochondrial' , 'extracellular region'
                    #  , 'nucleoplasm' , 'RNA binding' , 'cellular_component' , 'Spinal muscular atrophy, type I; Spinal
                    #  muscular atrophy, type II; Spinal muscular atrophy, type III; Spinal muscular atrophy, type IV' ,
                    #  'nucleus'
                    'xref_src_db': 'TEXT',
                    # EXAMPLES:
                    # 'ExpressionAtlas' , 'EnsemblGene' , 'GoComponent' , 'CGD' , 'EnsemblGene' , 'ExpressionAtlas' , 'G
                    # oFunction' , 'EnsemblGene' , 'CGD' , 'EnsemblGene'
                    'xref_src_url': 'TEXT',
                    # EXAMPLES:
                    # 'http://www.ebi.ac.uk/gxa/' , 'http://www.ensembl.org/' , 'http://www.ebi.ac.uk/QuickGO/' , 'http:
                    # //research.nhgri.nih.gov/CGD/' , 'http://www.ensembl.org/' , 'http://www.ebi.ac.uk/gxa/' , 'http:/
                    # /www.ebi.ac.uk/QuickGO/' , 'http://www.ensembl.org/' , 'http://research.nhgri.nih.gov/CGD/' , 'htt
                    # p://www.ensembl.org/'
                    'xref_url': 'TEXT',
                    # EXAMPLES:
                    # 'http://www.ebi.ac.uk/gxa/query?geneQuery=P13516' , 'http://www.ensembl.org/Gene/Summary?g=ENSG000
                    # 00146276' , 'http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005737' , 'http://research.nhgri.nih.gov/CG
                    # D/view/?g=MT-CO1' , 'http://www.ensembl.org/Gene/Summary?g=ENSG00000124731' , 'http://www.ebi.ac.u
                    # k/gxa/query?geneQuery=P00329' , 'http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003723' , 'http://www.e
                    # nsembl.org/Gene/Summary?g=ENSG00000149527' , 'http://research.nhgri.nih.gov/CGD/view/?g=SMN1' , 'h
                    # ttp://www.ensembl.org/Gene/Summary?g=ENSG00000169967'
                }
            },
            'targets': 
            {
                'properties': 
                {
                    'target_chembl_id': 'TEXT',
                    # EXAMPLES:
                    # 'CHEMBL5353' , 'CHEMBL3561' , 'CHEMBL2364672' , 'CHEMBL6173' , 'CHEMBL1697674' , 'CHEMBL4296289' ,
                    #  'CHEMBL1293232' , 'CHEMBL5914' , 'CHEMBL3196' , 'CHEMBL1075253'
                }
            },
            'tax_id': 'NUMERIC',
            # EXAMPLES:
            # '10090' , '9606' , '83333' , '9606' , '9606' , '10090' , '500046' , '9606' , '9606' , '9606'
        }
    }
