# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-31 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UciInchi',
            fields=[
                ('uci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('standardinchi', models.CharField(max_length=4000)),
                ('standardinchikey', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'uc_inchi',
                'managed': False,
            },
        ),
    ]
