glados.useNameSpace 'glados.models.paginatedCollections.esSchema',
  # The contents of this file were generated from the GLaDOS-es project
  GLaDOS_es_GeneratedSchema:
    chembl_activity:
      "activity_comment" : {type: String, aggregatable: true}
      "activity_id" : {type: String, aggregatable: true}
      "assay_chembl_id" : {type: String, aggregatable: true}
      "assay_description" : {type: String, aggregatable: false}
      "assay_type" : {type: String, aggregatable: true}
      "bao_endpoint" : {type: String, aggregatable: true}
      "bao_format" : {type: String, aggregatable: true}
      "canonical_smiles" : {type: String, aggregatable: true}
      "data_validity_comment" : {type: String, aggregatable: false}
      "document_chembl_id" : {type: String, aggregatable: true}
      "document_journal" : {type: String, aggregatable: true}
      "document_year" : {type: Number, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
      "pchembl_value" : {type: Number, aggregatable: true}
      "potential_duplicate" : {type: Boolean, aggregatable: true}
      "published_relation" : {type: String, aggregatable: true}
      "published_type" : {type: String, aggregatable: true}
      "published_units" : {type: String, aggregatable: true}
      "published_value" : {type: Number, aggregatable: true}
      "qudt_units" : {type: String, aggregatable: true}
      "record_id" : {type: String, aggregatable: true}
      "src_id" : {type: String, aggregatable: true}
      "standard_flag" : {type: Boolean, aggregatable: true}
      "standard_relation" : {type: String, aggregatable: true}
      "standard_type" : {type: String, aggregatable: true}
      "standard_units" : {type: String, aggregatable: true}
      "standard_value" : {type: Number, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
      "target_organism" : {type: String, aggregatable: true}
      "target_pref_name" : {type: String, aggregatable: false}
      "uo_units" : {type: String, aggregatable: true}
    chembl_assay:
      "assay_category" : {type: String, aggregatable: true}
      "assay_cell_type" : {type: String, aggregatable: true}
      "assay_chembl_id" : {type: String, aggregatable: true}
      "assay_organism" : {type: String, aggregatable: true}
      "assay_strain" : {type: String, aggregatable: true}
      "assay_subcellular_fraction" : {type: String, aggregatable: true}
      "assay_tax_id" : {type: String, aggregatable: true}
      "assay_test_type" : {type: String, aggregatable: true}
      "assay_tissue" : {type: String, aggregatable: true}
      "assay_type" : {type: String, aggregatable: true}
      "assay_type_description" : {type: String, aggregatable: true}
      "bao_format" : {type: String, aggregatable: true}
      "cell_chembl_id" : {type: String, aggregatable: true}
      "confidence_description" : {type: String, aggregatable: true}
      "confidence_score" : {type: Number, aggregatable: true}
      "description" : {type: String, aggregatable: false}
      "document_chembl_id" : {type: String, aggregatable: true}
      "relationship_description" : {type: String, aggregatable: true}
      "relationship_type" : {type: String, aggregatable: true}
      "src_assay_id" : {type: String, aggregatable: true}
      "src_id" : {type: String, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
      "tissue_chembl_id" : {type: String, aggregatable: true}
    chembl_atc_class:
      "level1" : {type: String, aggregatable: true}
      "level1_description" : {type: String, aggregatable: true}
      "level2" : {type: String, aggregatable: true}
      "level2_description" : {type: String, aggregatable: true}
      "level3" : {type: String, aggregatable: true}
      "level3_description" : {type: String, aggregatable: true}
      "level4" : {type: String, aggregatable: true}
      "level4_description" : {type: String, aggregatable: true}
      "level5" : {type: String, aggregatable: true}
      "who_id" : {type: String, aggregatable: true}
      "who_name" : {type: String, aggregatable: true}
    chembl_binding_site:
      "site_components.domain.domain_id" : {type: String, aggregatable: true}
      "site_components.domain.domain_name" : {type: String, aggregatable: true}
      "site_components.domain.domain_type" : {type: String, aggregatable: true}
      "site_components.domain.source_domain_id" : {type: String, aggregatable: true}
      "site_components.sitecomp_id" : {type: String, aggregatable: true}
      "site_id" : {type: String, aggregatable: true}
      "site_name" : {type: String, aggregatable: false}
    chembl_biotherapeutic:
      "biocomponents.component_id" : {type: String, aggregatable: true}
      "biocomponents.component_type" : {type: String, aggregatable: true}
      "biocomponents.description" : {type: String, aggregatable: false}
      "biocomponents.organism" : {type: String, aggregatable: true}
      "biocomponents.sequence" : {type: String, aggregatable: true}
      "biocomponents.tax_id" : {type: String, aggregatable: true}
      "description" : {type: String, aggregatable: false}
      "helm_notation" : {type: String, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
    chembl_cell_line:
      "cell_chembl_id" : {type: String, aggregatable: true}
      "cell_description" : {type: String, aggregatable: true}
      "cell_id" : {type: String, aggregatable: true}
      "cell_name" : {type: String, aggregatable: false}
      "cell_source_organism" : {type: String, aggregatable: true}
      "cell_source_tax_id" : {type: String, aggregatable: true}
      "cell_source_tissue" : {type: String, aggregatable: true}
      "cellosaurus_id" : {type: String, aggregatable: true}
      "cl_lincs_id" : {type: String, aggregatable: true}
      "clo_id" : {type: String, aggregatable: true}
      "efo_id" : {type: String, aggregatable: true}
    chembl_chembl_id_lookup:
      "chembl_id" : {type: String, aggregatable: true}
      "chembl_id_number" : {type: Number, aggregatable: true}
      "entity_type" : {type: String, aggregatable: true}
      "resource_url" : {type: String, aggregatable: true}
      "status" : {type: String, aggregatable: true}
    chembl_document:
      "abstract" : {type: String, aggregatable: false}
      "authors" : {type: String, aggregatable: false}
      "doc_type" : {type: String, aggregatable: true}
      "document_chembl_id" : {type: String, aggregatable: true}
      "doi" : {type: String, aggregatable: true}
      "first_page" : {type: String, aggregatable: true}
      "issue" : {type: String, aggregatable: true}
      "journal" : {type: String, aggregatable: true}
      "last_page" : {type: String, aggregatable: true}
      "pubmed_id" : {type: String, aggregatable: true}
      "title" : {type: String, aggregatable: false}
      "volume" : {type: Number, aggregatable: true}
      "year" : {type: Number, aggregatable: true}
    chembl_drug_indication:
      "drugind_id" : {type: String, aggregatable: true}
      "efo_id" : {type: String, aggregatable: true}
      "efo_term" : {type: String, aggregatable: false}
      "indication_refs.ref_id" : {type: String, aggregatable: true}
      "indication_refs.ref_type" : {type: String, aggregatable: true}
      "indication_refs.ref_url" : {type: String, aggregatable: true}
      "max_phase_for_ind" : {type: Number, aggregatable: true}
      "mesh_heading" : {type: String, aggregatable: false}
      "mesh_id" : {type: String, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
    chembl_go_slim:
      "aspect" : {type: String, aggregatable: true}
      "class_level" : {type: Number, aggregatable: true}
      "go_id" : {type: String, aggregatable: true}
      "parent_go_id" : {type: String, aggregatable: true}
      "path" : {type: String, aggregatable: false}
      "pref_name" : {type: String, aggregatable: false}
    chembl_mechanism:
      "action_type" : {type: String, aggregatable: true}
      "binding_site_comment" : {type: String, aggregatable: false}
      "direct_interaction" : {type: Boolean, aggregatable: true}
      "disease_efficacy" : {type: Boolean, aggregatable: true}
      "max_phase" : {type: Number, aggregatable: true}
      "mec_id" : {type: String, aggregatable: true}
      "mechanism_comment" : {type: String, aggregatable: false}
      "mechanism_of_action" : {type: String, aggregatable: false}
      "mechanism_refs.ref_id" : {type: String, aggregatable: true}
      "mechanism_refs.ref_type" : {type: String, aggregatable: true}
      "mechanism_refs.ref_url" : {type: String, aggregatable: true}
      "molecular_mechanism" : {type: Boolean, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
      "record_id" : {type: String, aggregatable: true}
      "selectivity_comment" : {type: String, aggregatable: true}
      "site_id" : {type: String, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
    chembl_metabolism:
      "drug_chembl_id" : {type: String, aggregatable: true}
      "enzyme_name" : {type: String, aggregatable: true}
      "met_comment" : {type: String, aggregatable: false}
      "met_conversion" : {type: String, aggregatable: false}
      "met_id" : {type: String, aggregatable: true}
      "metabolism_refs.ref_id" : {type: String, aggregatable: true}
      "metabolism_refs.ref_type" : {type: String, aggregatable: true}
      "metabolism_refs.ref_url" : {type: String, aggregatable: true}
      "metabolite_chembl_id" : {type: String, aggregatable: true}
      "organism" : {type: String, aggregatable: true}
      "pathway_id" : {type: String, aggregatable: true}
      "pathway_key" : {type: String, aggregatable: true}
      "substrate_chembl_id" : {type: String, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
      "tax_id" : {type: String, aggregatable: true}
    chembl_molecule:
      "atc_classifications" : {type: String, aggregatable: true}
      "availability_type" : {type: Number, aggregatable: true}
      "biotherapeutic.biocomponents.component_id" : {type: String, aggregatable: true}
      "biotherapeutic.biocomponents.component_type" : {type: String, aggregatable: true}
      "biotherapeutic.biocomponents.description" : {type: String, aggregatable: false}
      "biotherapeutic.biocomponents.organism" : {type: String, aggregatable: true}
      "biotherapeutic.biocomponents.sequence" : {type: String, aggregatable: true}
      "biotherapeutic.biocomponents.tax_id" : {type: String, aggregatable: true}
      "biotherapeutic.description" : {type: String, aggregatable: false}
      "biotherapeutic.helm_notation" : {type: String, aggregatable: true}
      "biotherapeutic.molecule_chembl_id" : {type: String, aggregatable: true}
      "black_box_warning" : {type: String, aggregatable: true}
      "chebi_par_id" : {type: String, aggregatable: true}
      "chirality" : {type: Number, aggregatable: true}
      "dosed_ingredient" : {type: Boolean, aggregatable: true}
      "first_approval" : {type: Number, aggregatable: true}
      "first_in_class" : {type: Number, aggregatable: true}
      "helm_notation" : {type: String, aggregatable: true}
      "indication_class" : {type: String, aggregatable: true}
      "inorganic_flag" : {type: Number, aggregatable: true}
      "max_phase" : {type: Number, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
      "molecule_hierarchy.molecule_chembl_id" : {type: String, aggregatable: true}
      "molecule_hierarchy.parent_chembl_id" : {type: String, aggregatable: true}
      "molecule_properties.acd_logd" : {type: Number, aggregatable: true}
      "molecule_properties.acd_logp" : {type: Number, aggregatable: true}
      "molecule_properties.acd_most_apka" : {type: Number, aggregatable: true}
      "molecule_properties.acd_most_bpka" : {type: Number, aggregatable: true}
      "molecule_properties.alogp" : {type: Number, aggregatable: true}
      "molecule_properties.aromatic_rings" : {type: Number, aggregatable: true}
      "molecule_properties.full_molformula" : {type: String, aggregatable: true}
      "molecule_properties.full_mwt" : {type: Number, aggregatable: true}
      "molecule_properties.hba" : {type: Number, aggregatable: true}
      "molecule_properties.hba_lipinski" : {type: Number, aggregatable: true}
      "molecule_properties.hbd" : {type: Number, aggregatable: true}
      "molecule_properties.hbd_lipinski" : {type: Number, aggregatable: true}
      "molecule_properties.heavy_atoms" : {type: Number, aggregatable: true}
      "molecule_properties.molecular_species" : {type: String, aggregatable: true}
      "molecule_properties.mw_freebase" : {type: Number, aggregatable: true}
      "molecule_properties.mw_monoisotopic" : {type: Number, aggregatable: true}
      "molecule_properties.num_alerts" : {type: Number, aggregatable: true}
      "molecule_properties.num_lipinski_ro5_violations" : {type: Number, aggregatable: true}
      "molecule_properties.num_ro5_violations" : {type: Number, aggregatable: true}
      "molecule_properties.psa" : {type: Number, aggregatable: true}
      "molecule_properties.qed_weighted" : {type: Number, aggregatable: true}
      "molecule_properties.ro3_pass" : {type: String, aggregatable: true}
      "molecule_properties.rtb" : {type: Number, aggregatable: true}
      "molecule_structures.canonical_smiles" : {type: String, aggregatable: true}
      "molecule_structures.standard_inchi" : {type: String, aggregatable: true}
      "molecule_structures.standard_inchi_key" : {type: String, aggregatable: true}
      "molecule_synonyms.molecule_synonym" : {type: String, aggregatable: false}
      "molecule_synonyms.syn_type" : {type: String, aggregatable: true}
      "molecule_synonyms.synonyms" : {type: String, aggregatable: false}
      "molecule_type" : {type: String, aggregatable: true}
      "natural_product" : {type: Number, aggregatable: true}
      "oral" : {type: Boolean, aggregatable: true}
      "parenteral" : {type: Boolean, aggregatable: true}
      "polymer_flag" : {type: Boolean, aggregatable: true}
      "pref_name" : {type: String, aggregatable: false}
      "prodrug" : {type: Number, aggregatable: true}
      "structure_type" : {type: String, aggregatable: true}
      "therapeutic_flag" : {type: Boolean, aggregatable: true}
      "topical" : {type: Boolean, aggregatable: true}
      "usan_stem_definition" : {type: String, aggregatable: false}
      "usan_substem" : {type: String, aggregatable: true}
      "usan_year" : {type: Number, aggregatable: true}
      "withdrawn_country" : {type: String, aggregatable: true}
      "withdrawn_flag" : {type: Boolean, aggregatable: true}
      "withdrawn_reason" : {type: String, aggregatable: false}
      "withdrawn_year" : {type: Number, aggregatable: true}
    chembl_molecule_form:
      "is_parent" : {type: Boolean, aggregatable: true}
      "molecule_chembl_id" : {type: String, aggregatable: true}
      "parent_chembl_id" : {type: String, aggregatable: true}
    chembl_protein_class:
      "l1" : {type: String, aggregatable: true}
      "l2" : {type: String, aggregatable: true}
      "l3" : {type: String, aggregatable: true}
      "l4" : {type: String, aggregatable: true}
      "l5" : {type: String, aggregatable: true}
      "l6" : {type: String, aggregatable: true}
      "protein_class_id" : {type: String, aggregatable: true}
    chembl_source:
      "src_description" : {type: String, aggregatable: true}
      "src_id" : {type: String, aggregatable: true}
      "src_short_name" : {type: String, aggregatable: true}
    chembl_target:
      "organism" : {type: String, aggregatable: true}
      "pref_name" : {type: String, aggregatable: false}
      "species_group_flag" : {type: Boolean, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
      "target_components.accession" : {type: String, aggregatable: true}
      "target_components.component_description" : {type: String, aggregatable: false}
      "target_components.component_id" : {type: String, aggregatable: true}
      "target_components.component_type" : {type: String, aggregatable: true}
      "target_components.relationship" : {type: String, aggregatable: true}
      "target_components.target_component_synonyms.component_synonym" : {type: String, aggregatable: false}
      "target_components.target_component_synonyms.syn_type" : {type: String, aggregatable: true}
      "target_type" : {type: String, aggregatable: true}
    chembl_target_component:
      "accession" : {type: String, aggregatable: true}
      "component_id" : {type: String, aggregatable: true}
      "component_type" : {type: String, aggregatable: true}
      "description" : {type: String, aggregatable: false}
      "go_slims.go_id" : {type: String, aggregatable: true}
      "organism" : {type: String, aggregatable: true}
      "protein_classifications.protein_classification_id" : {type: String, aggregatable: true}
      "sequence" : {type: String, aggregatable: true}
      "target_component_synonyms.component_synonym" : {type: String, aggregatable: true}
      "target_component_synonyms.syn_type" : {type: String, aggregatable: true}
      "targets.target_chembl_id" : {type: String, aggregatable: true}
      "tax_id" : {type: String, aggregatable: true}
    chembl_target_relation:
      "related_target_chembl_id" : {type: String, aggregatable: true}
      "relationship" : {type: String, aggregatable: true}
      "target_chembl_id" : {type: String, aggregatable: true}
    chembl_tissue:
      "efo_id" : {type: String, aggregatable: true}
      "pref_name" : {type: String, aggregatable: false}
      "tissue_chembl_id" : {type: String, aggregatable: true}
      "uberon_id" : {type: String, aggregatable: true}
