# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parentsmile',
            fields=[
                ('n_parent', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_smiles', models.CharField(max_length=4000)),
                ('inchikey', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'PARENTSMILES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUNDING', 'Funding')], default='FUNDING', max_length=20)),
                ('dates', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.CharField(blank=True, max_length=400, null=True)),
                ('is_current', models.IntegerField(choices=[('1', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default='1')),
            ],
            options={
                'db_table': 'acknowledgements',
            },
        ),
        migrations.CreateModel(
            name='ESCachedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_index', models.CharField(max_length=200)),
                ('es_query', models.TextField()),
                ('es_aggs', models.TextField()),
                ('es_request_digest', models.TextField()),
                ('is_cached', models.BooleanField()),
                ('host', models.TextField()),
                ('run_env_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=4000, null=True, unique=True)),
                ('answer', models.TextField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(default='0')),
            ],
            options={
                'db_table': 'faq_categories',
            },
        ),
        migrations.CreateModel(
            name='FaqSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faq_subcategories',
            },
        ),
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WizardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WizardOptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='wizardoption',
            name='parent_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.WizardStep'),
        ),
        migrations.AddField(
            model_name='wizardoption',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.WizardOptionType'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.FaqCategory'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.FaqSubcategory'),
        ),
    ]
