# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-28 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUNDING', 'Funding')], default='FUNDING', max_length=20)),
                ('dates', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.CharField(blank=True, max_length=400, null=True)),
                ('is_current', models.IntegerField(choices=[('1', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default='1')),
            ],
            options={
                'db_table': 'acknowledgements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=35)),
                ('region_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'COUNTRIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=4000, null=True, unique=True)),
                ('answer', models.TextField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(default='0')),
            ],
            options={
                'db_table': 'faq_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaqSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faq_subcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('hash', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=400)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardOptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ESCachedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_index', models.CharField(max_length=200)),
                ('es_query', models.TextField()),
                ('es_aggs', models.TextField()),
                ('es_request_digest', models.TextField()),
                ('is_cached', models.BooleanField()),
                ('host', models.TextField()),
                ('run_env_type', models.TextField()),
            ],
        ),
    ]
