# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=35)),
                ('region_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'COUNTRIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField(max_length=250)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('raw_columns_to_download', models.TextField(null=True)),
                ('raw_query', models.TextField(null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], default='QUEUED', max_length=20)),
                ('index_name', models.CharField(max_length=200, null=True)),
                ('desired_format', models.CharField(max_length=200, null=True)),
                ('worker', models.TextField(max_length=250, null=True)),
                ('log', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESCachedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_index', models.CharField(max_length=200)),
                ('es_query', models.TextField()),
                ('es_aggs', models.TextField()),
                ('es_request_digest', models.TextField()),
                ('is_cached', models.BooleanField()),
                ('host', models.TextField()),
                ('run_env_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ESDownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_id', models.TextField()),
                ('time_taken', models.IntegerField(default=0)),
                ('is_new', models.BooleanField()),
                ('file_size', models.BigIntegerField()),
                ('es_index', models.CharField(max_length=200)),
                ('es_query', models.TextField()),
                ('run_env_type', models.TextField()),
                ('desired_format', models.CharField(max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('host', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ESViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=20)),
                ('run_env_type', models.TextField()),
                ('host', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
    ]
