# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='id_property',
            field=models.CharField(max_length=100),
        ),
    ]
