# Generated by Django 2.2 on 2019-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
