# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esviewrecord',
            name='entity_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='esviewrecord',
            name='view_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='esviewrecord',
            name='view_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
