# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESSearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('FREE_TEXT', 'FREE_TEXT'), ('SUBSTRUCTURE', 'SUBSTRUCTURE'), ('SIMILARITY', 'SIMILARITY'), ('CONNECTIVITY', 'CONNECTIVITY'), ('BLAST', 'BLAST'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('run_env_type', models.TextField()),
                ('host', models.TextField(default='')),
            ],
        ),
    ]
