# Generated by Django 2.2 on 2019-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0002_downloadjob_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR'), ('DELETING', 'DELETING')], default='QUEUED', max_length=20),
        ),
    ]
