# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0002_auto_20160418_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='is_current',
            field=models.IntegerField(choices=[('1', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default='0'),
        ),
    ]
