# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0002_essearchrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.TextField(max_length=250)),
                ('context_id', models.TextField(max_length=250)),
                ('search_type', models.CharField(choices=[('SIMILARITY', 'SIMILARITY'), ('SUBSTRUCTURE', 'SUBSTRUCTURE'), ('CONNECTIVITY', 'CONNECTIVITY')], max_length=20)),
                ('status', models.CharField(choices=[('SEARCH_QUEUED', 'SEARCH_QUEUED'), ('SEARCHING', 'SEARCHING'), ('FINISHED', 'FINISHED')], max_length=20)),
                ('worker', models.TextField(max_length=250, null=True)),
                ('log', models.TextField(null=True)),
            ],
        ),
    ]
