# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0002_auto_20190319_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='expires',
            field=models.BigIntegerField(null=True),
        ),
    ]
