# Generated by Django 2.2 on 2019-05-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0003_auto_20190516_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sssearchjob',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
