# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0004_auto_20190213_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sssearchjob',
            name='status',
            field=models.CharField(choices=[('SEARCH_QUEUED', 'SEARCH_QUEUED'), ('SEARCHING', 'SEARCHING'), ('FINISHED', 'FINISHED')], default='SEARCH_QUEUED', max_length=20),
        ),
    ]
