# Generated by Django 2.2 on 2019-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0004_sssearchjob_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sssearchjob',
            name='status',
            field=models.CharField(choices=[('SEARCH_QUEUED', 'SEARCH_QUEUED'), ('SEARCHING', 'SEARCHING'), ('LOADING_RESULTS', 'LOADING_RESULTS'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR'), ('DELETING', 'DELETING')], default='SEARCH_QUEUED', max_length=20),
        ),
    ]
