# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-15 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0006_auto_20190214_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sssearchjob',
            name='context_id',
        ),
    ]
