# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0007_remove_sssearchjob_context_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='essearchrecord',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
