# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0008_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
