# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0008_essearchrecord_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='context_id',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='essearchrecord',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='downloadjob',
            name='job_id',
            field=models.TextField(max_length=500),
        ),
    ]
