# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0009_auto_20190221_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='id_property',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
