# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0010_downloadjob_id_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sssearchjob',
            name='search_type',
            field=models.CharField(choices=[('SIMILARITY', 'SIMILARITY'), ('SUBSTRUCTURE', 'SUBSTRUCTURE'), ('CONNECTIVITY', 'CONNECTIVITY'), ('BLAST', 'BLAST')], max_length=20),
        ),
    ]
