# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0011_auto_20160606_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLParams',
            fields=[
                ('hex_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('parameters', models.TextField()),
            ],
        ),
    ]
