# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0011_auto_20190227_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='sssearchjob',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
