# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0012_urlparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiryURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='URLParams',
        ),
    ]
