# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0012_sssearchjob_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sssearchjob',
            name='status',
            field=models.CharField(choices=[('SEARCH_QUEUED', 'SEARCH_QUEUED'), ('SEARCHING', 'SEARCHING'), ('LOADING_RESULTS', 'LOADING_RESULTS'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], default='SEARCH_QUEUED', max_length=20),
        ),
    ]
