# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-08 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0013_auto_20180308_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiryURL',
            new_name='TinyURL',
        ),
    ]
