# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0013_auto_20190301_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sssearchjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='sssearchjob',
            name='search_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
