# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0014_auto_20180308_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCachedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_index', models.CharField(max_length=200)),
                ('es_query', models.TextField()),
                ('es_aggs', models.TextField()),
                ('es_request_digest', models.TextField()),
                ('is_cached', models.BooleanField()),
                ('host', models.TextField()),
                ('run_env_type', models.TextField()),
            ],
        ),
    ]
