# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0014_auto_20190301_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadjob',
            name='job_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
