# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-04 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0016_auto_20190301_1622'),
    ]

    operations = []
