# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-07 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0017_remove_downloadjob_id'),
    ]

    operations = []
