# Elastic search mapping definition for the Molecule entity
from glados.es.ws2es.es_util import DefaultMappings

# Shards size - can be overridden from the default calculated value here
# shards = 3,
replicas = 1

analysis = DefaultMappings.COMMON_ANALYSIS

mappings = \
    {
        '_doc':
        {
            'properties': 
            {
                'accession': DefaultMappings.KEYWORD,
                # EXAMPLES:
                # 'P47870' , 'P62813' , 'P63079' , 'P63138' , 'Q00535' , 'Q00959' , 'Q00960' , 'Q00961' , 'Q00987' , 'Q0
                # 5586'
                'component_id': DefaultMappings.ID,
                # EXAMPLES:
                # '47' , '48' , '49' , '50' , '51' , '52' , '53' , '54' , '55' , '56'
                'component_type': DefaultMappings.KEYWORD,
                # EXAMPLES:
                # 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTEIN' , 'PROTE
                # IN' , 'PROTEIN'
                'description': DefaultMappings.TEXT_STD,
                # EXAMPLES:
                # 'Gamma-aminobutyric acid receptor subunit beta-2' , 'Gamma-aminobutyric acid receptor subunit alpha-1'
                #  , 'Gamma-aminobutyric acid receptor subunit beta-3' , 'Gamma-aminobutyric acid receptor subunit beta-
                # 2' , 'Cyclin-dependent-like kinase 5' , 'Glutamate receptor ionotropic, NMDA 2A' , 'Glutamate receptor
                #  ionotropic, NMDA 2B' , 'Glutamate receptor ionotropic, NMDA 2C' , 'E3 ubiquitin-protein ligase Mdm2' 
                # , 'Glutamate receptor ionotropic, NMDA 1'
                'go_slims': 
                {
                    'properties': 
                    {
                        'go_id': DefaultMappings.ID_REF,
                        # EXAMPLES:
                        # 'GO:0004871' , 'GO:0003674' , 'GO:0004871' , 'GO:0004871' , 'GO:0000166' , 'GO:0003674' , 'GO:
                        # 0003674' , 'GO:0004871' , 'GO:0005102' , 'GO:0000003'
                    }
                },
                'organism': DefaultMappings.LOWER_CASE_KEYWORD,
                # EXAMPLES:
                # 'Homo sapiens' , 'Rattus norvegicus' , 'Rattus norvegicus' , 'Rattus norvegicus' , 'Homo sapiens' , 'R
                # attus norvegicus' , 'Rattus norvegicus' , 'Rattus norvegicus' , 'Homo sapiens' , 'Homo sapiens'
                'protein_classifications': 
                {
                    'properties': 
                    {
                        'protein_classification_id': DefaultMappings.ID_REF,
                        # EXAMPLES:
                        # '1173' , '1173' , '1173' , '1173' , '325' , '1150' , '1150' , '1150' , '5' , '1150'
                    }
                },
                'sequence': DefaultMappings.KEYWORD,
                # EXAMPLES:
                # 'MWRVRKRGYFGIWSFPLIIAAVCAQSVNDPSNMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMVSEVNMDYTLTMYFQQAWRDKRLSYNVI
                # PLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRGDDNAVTGVT
                # KIELPQFSIVDYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTYMPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPYVKAI
                # DMYLMGCFVFVFMALLEYALVNYIFFGRGPQRQKKAAEKAASANNEKMRLDVNKIFYKDIKQNGTQYRSLWDPTGNLSPTRRTTNYDFSLYTMDPHENILLS
                # TLEIKNEMATSEAVMGLGDPRSTMLAYDASSIQYRKAGLPRHSFGRNALERHVAQKKSRLRRRASQLKITIPDLTDVNAIDRWSRIFFPVVFSFFNIVYWLY
                # YVN' , 'MKKSRGLSDYLWAWTLILSTLSGRSYGQPSQDELKDNTTVFTRILDRLLDGYDNRLRPGLGERVTEVKTDIFVTSFGPVSDHDMEYTIDVFFRQ
                # SWKDERLKFKGPMTVLRLNNLMASKIWTPDTFFHNGKKSVAHNMTMPNKLLRITEDGTLLYTMRLTVRAECPMHLEDFPMDAHACPLKFGSYAYTRAEVVYE
                # WTREPARSVVVAEDGSRLNQYDLLGQTVDSGIVQSSTGEYVVMTTHFHLKRKIGYFVIQTYLPCIMTVILSQVSFWLNRESVPARTVFGVTTVLTMTTLSIS
                # ARNSLPKVAYATAMDWFIAVCYAFVFSALIEFATVNYFTKRGYAWDGKSVVPEKPKKVKDPLIKKNNTYAPTATSYTPNLARGDPGLATIAKSATIEPKEVK
                # PETKPPEPKKTFNSVSKIDRLSRIAFPLLFGIFNLVYWATYLNREPQLKAPTPHQ' , 'MWGFAGGRLFGIFSAPVLVAVVCCAQSVNDPGNMSFVKETVD
                # KLLKGYDIRLRPDFGGPPVCVGMNIDIASIDMVSEVNMDYTLTMYFQQYWRDKRLAYSGIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLH
                # PDGTVLYGLRITTTAACMMDLRRYPLDEQNCTLEIESYGYTTDDIEFYWRGGDKAVTGVERIELPQFSIVEHRLVSRNVVFATGAYPRLSLSFRLKRNIGYF
                # ILQTYMPSILITILSWVSFWINYDASAARVALGITTVLTMTTINTHLRETLPKIPYVKAIDMYLMGCFVFVFLALLEYAFVNYIFFGRGPQRQKKLAEKTAK
                # AKNDRSKSEINRVDAHGNILLAPMDVHNEMNEVAGSVGDTRNSAISFDNSGIQYRKQSMPKEGHGRYMGDRSIPHKKTHLRRRSSQLKIKIPDLTDVNAIDR
                # WSRIVFPFTFSLFNLVYWLYYVN' , 'MWRVRKRGYFGIWSFPLIIAAVCAQSVNDPSNMSLVKETVDRLLKGYDIRLRPDFGGPPVAVGMNIDIASIDMV
                # SEVNMDYTLTMYFQQAWRDKRLSYNVIPLNLTLDNRVADQLWVPDTYFLNDKKSFVHGVTVKNRMIRLHPDGTVLYGLRITTTAACMMDLRRYPLDEQNCTL
                # EIESYGYTTDDIEFYWRGDDNAVTGVTKIELPQFSIVDYKLITKKVVFSTGSYPRLSLSFKLKRNIGYFILQTYMPSILITILSWVSFWINYDASAARVALG
                # ITTVLTMTTINTHLRETLPKIPYVKAIDMYLMGCFVFVFMALLEYALVNYIFFGRGPQRQKKAAEKAANANNEKMRLDVNKMDPHENILLSTLEIKNEMATS
                # EAVMGLGDPRSTMLAYDASSIQYRKAGLPRHSFGRNALERHVAQKKSRLRRRASQLKITIPDLTDVNAIDRWSRIFFPVVFSFFNIVYWLYYVN' , 'MQK
                # YEKLEKIGEGTYGTVFKAKNRETHEIVALKRVRLDDDDEGVPSSALREICLLKELKHKNIVRLHDVLHSDKKLTLVFEFCDQDLKKYFDSCNGDLDPEIVKS
                # FLFQLLKGLGFCHSRNVLHRDLKPQNLLINRNGELKLADFGLARAFGIPVRCYSAEVVTLWYRPPDVLFGAKLYSTSIDMWSAGCIFAELANAGRPLFPGND
                # VDDQLKRIFRLLGTPTEEQWPSMTKLPDYKPYPMYPATTSLVNVVPKLNATGRDLLQNLLKCNPVQRISAEEALQHPYFSDFCPP' , 'MGRLGYWTLLVL
                # PALLVWRDPAQNAAAEKGPPALNIAVLLGHSHDVTERELRNLWGPEQATGLPLDVNVVALLMNRTDPKSLITHVCDLMSGARIHGLVFGDDTDQEAVAQMLD
                # FISSQTFIPILGIHGGASMIMADKDPTSTFFQFGASIQQQATVMLKIMQDYDWHVFSLVTTIFPGYRDFISFIKTTVDNSFVGWDMQNVITLDTSFEDAKTQ
                # VQLKKIHSSVILLYCSKDEAVLILSEARSLGLTGYDFFWIVPSLVSGNTELIPKEFPSGLISVSYDDWDYSLEARVRDGLGILTTAASSMLEKFSYIPEAKA
                # SCYGQAEKPETPLHTLHQFMVNVTWDGKDLSFTEEGYQVHPRLVVIVLNKDREWEKVGKWENQTLSLRHAVWPRYKSFSDCEPDDNHLSIVTLEEAPFVIVE
                # DIDPLTETCVRNTVPCRKFVKINNSTNEGMNVKKCCKGFCIDILKKLSRTVKFTYDLYLVTNGKHGKKVNNVWNGMIGEVVYQRAVMAVGSLTINEERSEVV
                # DFSVPFVETGISVMVSRSNGTVSPSAFLEPFSASVWVMMFVMLLIVSAIAVFVFEYFSPVGYNRNLAKGKAPHGPSFTIGKAIWLLWGLVFNNSVPVQNPKG
                # TTSKIMVSVWAFFAVIFLASYTANLAAFMIQEEFVDQVTGLSDKKFQRPHDYSPPFRFGTVPNGSTERNIRNNYPYMHQYMTRFNQRGVEDALVSLKTGKLD
                # AFIYDAAVLNYKAGRDEGCKLVTIGSGYIFASTGYGIALQKGSPWKRQIDLALLQFVGDGEMEELETLWLTGICHNEKNEVMSSQLDIDNMAGVFYMLAAAM
                # ALSLITFIWEHLFYWKLRFCFTGVCSDRPGLLFSISRGIYSCIHGVHIEEKKKSPDFNLTGSQSNMLKLLRSAKNISNMSNMNSSRMDSPKRATDFIQRGSL
                # IVDMVSDKGNLIYSDNRSFQGKDSIFGDNMNELQTFVANRHKDNLSNYVFQGQHPLTLNESNPNTVEVAVSTESKGNSRPRQLWKKSMESLRQDSLNQNPVS
                # QRDEKTAENRTHSLKSPRYLPEEVAHSDISETSSRATCHREPDNNKNHKTKDNFKRSMASKYPKDCSDVDRTYMKTKASSPRDKIYTIDGEKEPSFHLDPPQ
                # FVENITLPENVGFPDTYQDHNENFRKGDSTLPMNRNPLHNEDGLPNNDQYKLYAKHFTLKDKGSPHSEGSDRYRQNSTHCRSCLSNLPTYSGHFTMRSPFKC
                # DACLRMGNLYDIDEDQMLQETGNPATREEVYQQDWSQNNALQFQKNKLRINRQHSYDNILDKPREIDLSRPSRSISLKDRERLLEGNLYGSLFSVPSSKLLG
                # NKSSLFPQGLEDSKRSKSLLPDHASDNPFLHTYGDDQRLVIGRCPSDPYKHSLPSQAVNDSYLRSSLRSTASYCSRDSRGHSDVYISEHVMPYAANKNTMYS
                # TPRVLNSCSNRRVYKKMPSIESDV' , 'MKPSAECCSPKFWLVLAVLAVSGSKARSQKSPPSIGIAVILVGTSDEVAIKDAHEKDDFHHLSVVPRVELVAM
                # NETDPKSIITRICDLMSDRKIQGVVFADDTDQEAIAQILDFISAQTLTPILGIHGGSSMIMADKDESSMFFQFGPSIEQQASVMLNIMEEYDWYIFSIVTTY
                # FPGYQDFVNKIRSTIENSFVGWELEEVLLLDMSLDDGDSKIQNQLKKLQSPIILLYCTKEEATYIFEVANSVGLTGYGYTWIVPSLVAGDTDTVPSEFPTGL
                # ISVSYDEWDYGLPARVRDGIAIITTAASDMLSEHSFIPEPKSSCYNTHEKRIYQSNMLNRYLINVTFEGRNLSFSEDGYQMHPKLVIILLNKERKWERVGKW
                # KDKSLQMKYYVWPRMCPETEEQEDDHLSIVTLEEAPFVIVESVDPLSGTCMRNTVPCQKRIISENKTDEEPGYIKKCCKGFCIDILKKISKSVKFTYDLYLV
                # TNGKHGKKINGTWNGMIGEVVMKRAYMAVGSLTINEERSEVVDFSVPFIETGISVMVSRSNGTVSPSAFLEPFSADVWVMMFVMLLIVSAVAVFVFEYFSPV
                # GYNRCLADGREPGGPSFTIGKAIWLLWGLVFNNSVPVQNPKGTTSKIMVSVWAFFAVIFLASYTANLAAFMIQEEYVDQVSGLSDKKFQRPNDFSPPFRFGT
                # VPNGSTERNIRNNYAEMHAYMGKFNQRGVDDALLSLKTGKLDAFIYDAAVLNYMAGRDEGCKLVTIGSGKVFASTGYGIAIQKDSGWKRQVDLAILQLFGDG
                # EMEELEALWLTGICHNEKNEVMSSQLDIDNMAGVFYMLGAAMALSLITFICEHLFYWQFRHCFMGVCSGKPGMVFSISRGIYSCIHGVAIEERQSVMNSPTA
                # TMNNTHSNILRLLRTAKNMANLSGVNGSPQSALDFIRRESSVYDISEHRRSFTHSDCKSYNNPPCEENLFSDYISEVERTFGNLQLKDSNVYQDHYHHHHRP
                # HSIGSTSSIDGLYDCDNPPFTTQPRSISKKPLDIGLPSSKHSQLSDLYGKFSFKSDRYSGHDDLIRSDVSDISTHTVTYGNIEGNAAKRRKQQYKDSLKKRP
                # ASAKSRREFDEIELAYRRRPPRSPDHKRYFRDKEGLRDFYLDQFRTKENSPHWEHVDLTDIYKERSDDFKRDSVSGGGPCTNRSHLKHGTGEKHGVVGGVPA
                # PWEKNLTNVDWEDRSGGNFCRSCPSKLHNYSSTVAGQNSGRQACIRCEACKKAGNLYDISEDNSLQELDQPAAPVAVTSNASSTKYPQSPTNSKAQKKNRNK
                # LRRQHSYDTFVDLQKEEAALAPRSVSLKDKGRFMDGSPYAHMFEMPAGESSFANKSSVPTAGHHHNNPGSGYMLSKSLYPDRVTQNPFIPTFGDDQCLLHGS
                # KSYFFRQPTVAGASKTRPDFRALVTNKPVVVTLHGAVPGRFQKDICIGNQSNPCVPNNKNPRAFNGSSNGHVYEKLSSIESDV' , 'MGGALGPALLLTSL
                # LGAWARLGAGQGEQAVTVAVVFGSSGPLQTQARTRLTSQNFLDLPLEIQPLTVGVNNTNPSSILTQICGLLGAARVHGIVFEDNVDTEAVAQLLDFVSSQTH
                # VPILSISGGSAVVLTPKEPGSAFLQLGVSLEQQLQVLFKVLEEYDWSAFAVITSLHPGHALFLEGVRAVADASYLSWRLLDVLTLELGPGGPRARTQRLLRQ
                # VDAPVLVAYCSREEAEVLFAEAAQAGLVGPGHVWLVPNLALGSTDAPPAAFPVGLISVVTESWRLSLRQKVRDGVAILALGAHSYRRQYGTLPAPAGDCRSH
                # PGPVSPAREAFYRHLLNVTWEGRDFSFSPGGYLVRPTMVVIALNRHRLWEMVGRWDHGVLYMKYPVWPRYSTSLQPVVDSRHLTVATLEERPFVIVESPDPG
                # TGGCVPNTVPCRRQSNHTFSSGDLTPYTKLCCKGFCIDILKKLAKVVKFSYDLYLVTNGKHGKRVRGVWNGMIGEVYYKRADMAIGSLTINEERSEIIDFSV
                # PFVETGISVMVSRSNGTVSPSAFLEPYSPAVWVMMFVMCLTVVAITVFMFEYFSPVSYNQNLTKGKKPGGPSFTIGKSVWLLWALVFNNSVPIENPRGTTSK
                # IMVLVWAFFAVIFLASYTANLAAFMIQEQYIDTVSGLSDKKFQRPQDQYPPFRFGTVPNGSTERNIRSNYRDMHTHMVKFNQRSVEDALTSLKMGKLDAFIY
                # DAAVLNYMAGKDEGCKLVTIGSGKVFATTGYGIAMQKDSHWKRAIDLALLQLLGDGETQKLETVWLSGICQNEKNEVMSSKLDIDNMAGVFYMLLVAMGLAL
                # LVFAWEHLVYWKLRHSVPNSSQLDFLLAFSRGIYSCFNGVQSLPSPARPPSPDLTADSAQANVLKMLQAARDMVNTADVSSSLDRATRTIENWGNNRRVPAP
                # TASGPRSSTPGPPGQPSPSGWGPPGGGRTPLARRAPQPPARPATCGPPLPDVSRPSCRHASDARWPVRVGHQGPHVSASERRALPERSLLPAHCHYSSFPRA
                # ERSGRPYLPLFPEPPEPDDLPLLGPEQLARREAMLRAAWARGPRPRHASLPSSVAEAFTRSNPLPARCTGHACACPCPQSRPSCRHLAQAQSLRLPSYPEAC
                # VEGVPAGVATWQPRQHVCLHAHTRLPFCWGTVCRHPPPCTSHSPWLIGTWEPPAHRVRTLGLGTGYRDSGVLEEVSREACGTQGFPRSCTWRRVSSLESEV'
                #  , 'MCNTNMSVPTDGAVTTSQIPASEQETLVRPKPLLLKLLKSVGAQKDTYTMKEVLFYLGQYIMTKRLYDEKQQHIVYCSNDLLGDLFGVPSFSVKEHRK
                # IYTMIYRNLVVVNQQESSDSGTSVSENRCHLEGGSDQKDLVQELQEEKPSSSHLVSRPSTSSRRRAISETEENSDELSGERQRKRHKSDSISLSFDESLALC
                # VIREICCERSSSSESTGTPSNPDLDAGVSEHSGDWLDQDSVSDQFSVEFEVESLDSEDYSLSEEGQELSDEDDEVYQVTVYQAGESDTDSFEEDPEISLADY
                # WKCTSCNEMNPPLPSHCNRCWALRENWLPEDKGKDKGEISEKAKLENSTQAEEGFDVPDCKKTIVNDSRESCVEENDDKITQASQSQESEDYSQPSTSSSII
                # YSSQEDVKEFEREETQDKEESVESSLPLNAIEPCVICQGRPKNGCIVHGKTGHLMACFTCAKKLKKRNKPCPVCRQPIQMIVLTYFP' , 'MSTMRLLTLA
                # LLFSCSVARAACDPKIVNIGAVLSTRKHEQMFREAVNQANKRHGSWKIQLNATSVTHKPNAIQMALSVCEDLISSQVYAILVSHPPTPNDHFTPTPVSYTAG
                # FYRIPVLGLTTRMSIYSDKSIHLSFLRTVPPYSHQSSVWFEMMRVYSWNHIILLVSDDHEGRAAQKRLETLLEERESKAEKVLQFDPGTKNVTALLMEAKEL
                # EARVIILSASEDDAATVYRAAAMLNMTGSGYVWLVGEREISGNALRYAPDGILGLQLINGKNESAHISDAVGVVAQAVHELLEKENITDPPRGCVGNTNIWK
                # TGPLFKRVLMSSKYADGVTGRVEFNEDGDRKFANYSIMNLQNRKLVQVGIYNGTHVIPNDRKIIWPGGETEKPRGYQMSTRLKIVTIHQEPFVYVKPTLSDG
                # TCKEEFTVNGDPVKKVICTGPNDTSPGSPRHTVPQCCYGFCIDLLIKLARTMNFTYEVHLVADGKFGTQERVNNSNKKEWNGMMGELLSGQADMIVAPLTIN
                # NERAQYIEFSKPFKYQGLTILVKKEIPRSTLDSFMQPFQSTLWLLVGLSVHVVAVMLYLLDRFSPFGRFKVNSEEEEEDALTLSSAMWFSWGVLLNSGIGEG
                # APRSFSARILGMVWAGFAMIIVASYTANLAAFLVLDRPEERITGINDPRLRNPSDKFIYATVKQSSVDIYFRRQVELSTMYRHMEKHNYESAAEAIQAVRDN
                # KLHAFIWDSAVLEFEASQKCDLVTTGELFFRSGFGIGMRKDSPWKQNVSLSILKSHENGFMEDLDKTWVRYQECDSRSNAPATLTFENMAGVFMLVAGGIVA
                # GIFLIFIEIAYKRHKDARRKQMQLAFAAVNVWRKNLQDRKSGRAEPDPKKKATFRAITSTLASSFKRRRSSKDTSTGGGRGALQNQKDTVLPRRAIEREEGQ
                # LQLCSRHRES'
                'target_component_synonyms': 
                {
                    'properties': 
                    {
                        'component_synonym': DefaultMappings.KEYWORD,
                        # EXAMPLES:
                        # 'GABRB2' , 'Gabra-1' , 'Gabrb-3' , 'Gabrb-2' , 'CDKN5' , 'Grin2a' , 'Grin2b' , 'Grin2c' , 'MDM
                        # 2' , 'NMDAR1'
                        'syn_type': DefaultMappings.KEYWORD,
                        # EXAMPLES:
                        # 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL' 
                        # , 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL' , 'GENE_SYMBOL'
                    }
                },
                'target_component_xrefs': {
                    'properties': {
                        'xref_id': DefaultMappings.KEYWORD,
                        'xref_name': DefaultMappings.KEYWORD,
                        'xref_src_db': DefaultMappings.KEYWORD
                    }
                },
                'targets': 
                {
                    'properties': 
                    {
                        'target_chembl_id': DefaultMappings.CHEMBL_ID_REF,
                        # EXAMPLES:
                        # 'CHEMBL1920' , 'CHEMBL343' , 'CHEMBL2096683' , 'CHEMBL2095167' , 'CHEMBL4036' , 'CHEMBL310' , 
                        # 'CHEMBL311' , 'CHEMBL401' , 'CHEMBL5023' , 'CHEMBL2015'
                    }
                },
                'tax_id': DefaultMappings.ID_REF,
                # EXAMPLES:
                # '9606' , '10116' , '10116' , '10116' , '9606' , '10116' , '10116' , '10116' , '9606' , '9606'
            }
        }
    }
