# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('dates', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.CharField(blank=True, max_length=400, null=True)),
                ('is_current', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acknowledgements',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=4000, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('deleted', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faq_categories',
            },
        ),
        migrations.CreateModel(
            name='FaqSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faq_subcategories',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.FaqCategory'),
        ),
        migrations.AddField(
            model_name='faq',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.FaqSubcategory'),
        ),
    ]
