# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0003_auto_20160418_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='category',
            field=models.CharField(choices=[('FUNDING', 'Funding')], default='FUNDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='is_current',
            field=models.IntegerField(choices=[('1', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default='1'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
