# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0004_auto_20160510_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
