# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0006_auto_20160510_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
