# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0009_delete_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WizardOptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='wizardoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.WizardStep'),
        ),
        migrations.AddField(
            model_name='wizardoption',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glados.WizardOptionType'),
        ),
    ]
