# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glados', '0010_auto_20160606_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizardoption',
            old_name='option',
            new_name='parent_step',
        ),
    ]
